### ISSUE TITLE
Add new `Evidence: Template Project Url` extension Setting

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#62]
to allow users to set their own local or remote Evidence template Url in extension Settings.

- [x] add `evidence.templateProjectUrl` string setting to `package.json`
- [x] default it to the Evidence `template` github repo Url for now
- [x] use this new `evidence.templateProjectUrl` setting in `project.ts` when creating new projects
- [x] check for `file://` or `https://` template project Uri scheme to determine if we need to load it from local file system or github repo via cloning added in #48 
- [x] test it with cloned Evidence `template` repo and local fs
- [x] update #48 to either copy local project folder or clone it from github based on the template Url scheme entered in the displayed template Url prompt
- [x] test new embedded Evidence project `/template` added in #61 by changing this setting to `/template` extension folder path
- [x] update Settings section in `README.md` with this new setting info
- [x] change this setting to use new embedded `/template` folder by default for faster `New Evidence Project` and `Evidence Project from Template` project creation and onboarding user experience.

**Comment by RandomFractals** [comment]
New Evidence Template Project Url Setting displayed when you view Evidence settings using new View Settings command from #55 

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/514f3555-cd5d-4df3-91b3-0dd082f42010)

**Comment by RandomFractals** [comment]
`New Evidence Project` command using this new `evidence.templateProjectUrl` setting with github url, and cloning that repo:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/a10e2955-a43d-4484-9461-a3ca8ab2748c)

**Comment by RandomFractals** [comment]
When invalid github url is provided in new `evidence.templateProjectUrl` setting:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/97100e9f-b07a-44ac-9a4d-14856a5b850e)

**Comment by RandomFractals** [comment]
Error message displayed when invalid template project Url is provided, i.e. not using `https://` or `file://`:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/420766c0-8e46-4dfe-9e40-e69d73c370bf)

**Comment by RandomFractals** [comment]
Invalid local template project folder error message and output logging display:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/4ae0bd6f-454f-45a3-9d67-5c2ab8208b23)

**Comment by RandomFractals** [comment]
Output view messages and prompt to open created project folder when a valid `file://` template project Url is provided:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/99ddcef6-c00b-49bf-b6e2-9fb3d076c085)

**Comment by RandomFractals** [comment]
New and improved instance new Evidane project creation from a local template folder:

![evidence-project-new-from-local-template](https://github.com/evidence-dev/evidence-vscode/assets/656833/af0a35f3-77c1-4fd2-aa5b-717f40976ec1)

**Comment by RandomFractals** [comment]
will need to finalize this for the `v1.1.0` release too (#64)

**Comment by RandomFractals** [comment]
Updated Settings section with new `evidence.templateProjectUrl` info in md table and `settings.json` config example in docs:

https://github.com/evidence-dev/evidence-vscode#evidence-settings

**Comment by RandomFractals** [comment]
Using `/template` folder from this repo for the default template project url and cloning to create new project:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/324ecb96-390e-4a56-b121-1d812eacc97a)

**Comment by RandomFractals** [comment]
We can set `/template` as default once we can confirm #72 works on Mac OS as expected.

**Comment by RandomFractals** [comment]
New `evidence.templateProjectUrl` default and description displayed in the built-in VS Code Settings editor:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/0f294358-e233-4dcf-ab8e-b29fd7e55dac)

**Comment by RandomFractals** [comment]
> File setting description v.:
> 
> ![image](https://user-images.githubusercontent.com/656833/243762755-d2d1a54a-6496-4efb-981e-238cf9905744.png)

**Comment by RandomFractals** [comment]
See updated and final Settings section in docs for the v1.1.0 release:

https://github.com/evidence-dev/evidence-vscode#evidence-settings
